### ISSUE TITLE
报了一堆phantomjs的错误

### ISSUE THREAD

**Issue by linkerlin** [ryh95/pyspider-stock#1]
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:362:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
internal/child_process.js:274
  var err = this._handle.spawn(options);
                         ^

**Comment by linkerlin** [comment]
似乎是phantomjs改了api？

**Comment by ryh95** [comment]
我没有改phantomjs相关的东西，有可能是改了API

**Comment by linkerlin** [comment]
我把phantomjs删除后就好了。

**Comment by ryh95** [comment]
我之前装的时候没有出过错 可能是版本问题 或者环境问题 你安装的时候没错 抓雪球的时候出错了是吗
