### ISSUE TITLE
最后一步做情感分析的时候pymongo报错

### ISSUE THREAD

**Issue by linkerlin** [ryh95/pyspider-stock#3]
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    aggregateFactor.aggregate(stockCode, grab_time)
  File "/Users/linkerlin/gits/pyspider-stock/east_sentiment/aggregateFactor.py", line 22, in aggregate
    for result in documents['result']:
TypeError: 'CommandCursor' object has no attribute '__getitem__'

**Comment by linkerlin** [comment]
```
    coll2 = db[date+'SentimentFactor']
    for result in documents['result']:
        coll2.insert_one({
            "sentiment_factor": result['sentiment_factor'],
            "last_date": date
        })

问题出在for 这一行。 documents[]的写法貌似不对

**Comment by ryh95** [comment]
pymongo因为一些原因暂时不要用高版本的，如果没记错的话用<=2.0版本的，这个我后面修复下
